### PR TITLE
Fixed projection for lazy discrete operator

### LINKED ISSUE #30: Apply overapproximation for Filtered Oscillator model to project LazyTextbookDiscretePost solution

### PR DESCRIPTION
**Pull request by kostakoida**
Close #30

### CODE REVIEW

File: models/SpaceEx/FilteredOscillator/FilteredOscillator.jl [hunk 1]
```diff
@@ -93,21 +92,33 @@ X0 = Hyperrectangle(low=[0.2; -0.1 * ones(system_dimension-1)],
...
+                  :plot_vars=>plot_vars, :max_jumps=>4,
                   :partition=>[1:system_dimension], :ε_proj=>0.001,
                   :clustering=>:chull, :verbosity=>1);
 
-# default algorithm
-sol = solve(system, options);
+options_proj_false = Options(:project_reachset=>false)
+options_proj_true = Options(:project_reachset=>true)
+
+options_pr_t = merge!(options_common, options_proj_true)
```
Comment (schillic) [inline models/SpaceEx/FilteredOscillator/FilteredOscillator.jl]: Use `merge` (without `!`). Or just make a copy manually and write `options_copy.dict[:project_reachset] = true/false`.

File: models/SpaceEx/FilteredOscillator/FilteredOscillator.jl [hunk 2]
```diff
@@ -93,21 +92,33 @@ X0 = Hyperrectangle(low=[0.2; -0.1 * ones(system_dimension-1)],
...
+# default algorithm
+sol = solve(system, options_pr_t);
 # specify lazy discrete post operator
-sol = solve(system, options, Reachability.BFFPSV18(),
+sol = solve(system, options_pr_f, Reachability.BFFPSV18(),
             Reachability.ReachSets.LazyTextbookDiscretePost());
 
+N = Float64
+sol_processed =  Reachability.ReachSolution([Reachability.ReachSet{CartesianProductArray{N}, N}(
+            CartesianProductArray{N, HPolytope{N}}([LazySets.Approximations.overapproximate(rs.X, LazySets.Approximations.OctDirections(4))]),
```
Comment (schillic) [inline models/SpaceEx/FilteredOscillator/FilteredOscillator.jl]: Do not hard-code the `4` here.
